import type { Metadata } from 'next';
import DashboardWrapper from '@/components/DashboardWrapper/DashboardWrapper';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
